on:
  schedule:
    - cron: '9 5 * * *'
  push:
    branches:
      - 'master'

jobs:
  update-apod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node_version: '14'

      - run: npm install jsdom
      - run: wget 'https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY' -O apod.json
      - run: node .github/workflows/update-apod.js apod.json
      - uses: test-room-7/action-update-file@v1.6.0
        with:
          file-path: index.html
          commit-msg: Update index.html
          github-token: ${{ secrets.GITHUB_TOKEN }}
